#!/bin/bash

quda_src=~/code/2019_12_04/quda_for_plugin

source ${quda_src}/build_PizDaint_2019_12_04/PizDaint_load_modules_hdf5-parallel.sh

cmake --version

cmake -DGIT_EXECUTABLE=/usr/bin/git \
  -DCMAKE_C_COMPILER=cc \
  -DCMAKE_CXX_COMPILER=CC \
  -DCMAKE_BUILD_TYPE=DEVEL \
  -DQUDA_ARPACK=OFF \
  -DQUDA_BLOCKSOLVER=OFF \
  -DQUDA_CONTRACT=ON \
  -DQUDA_DEFLATEDSOLVER=OFF \
  -DQUDA_DIRAC_CLOVER=ON \
  -DQUDA_DIRAC_DOMAIN_WALL=OFF \
  -DQUDA_DIRAC_NDEG_TWISTED_MASS=OFF \
  -DQUDA_DIRAC_STAGGERED=OFF \
  -DQUDA_DIRAC_TWISTED_CLOVER=ON \
  -DQUDA_DIRAC_TWISTED_MASS=ON \
  -DQUDA_DIRAC_WILSON=ON \
  -DQUDA_DOWNLOAD_EIGEN=ON \
  -DQUDA_DYNAMIC_CLOVER=OFF \
  -DQUDA_FORCE_ASQTAD=OFF \
  -DQUDA_FORCE_GAUGE=OFF \
  -DQUDA_FORCE_HISQ=OFF \
  -DQUDA_GAUGE_ALG=OFF \
  -DQUDA_GAUGE_TOOLS=OFF \
  -DQUDA_GPU_ARCH=sm_60 \
  -DQUDA_INTERFACE_BQCD=OFF \
  -DQUDA_INTERFACE_CPS=OFF \
  -DQUDA_INTERFACE_MILC=ON \
  -DQUDA_INTERFACE_QDP=ON \
  -DQUDA_INTERFACE_QDPJIT=OFF \
  -DQUDA_INTERFACE_TIFR=OFF \
  -DQUDA_LINK_ASQTAD=OFF \
  -DQUDA_LINK_HISQ=OFF \
  -DQUDA_MAGMA=OFF \
  -DQUDA_MPI=ON \
  -DQUDA_MULTIGRID=ON \
  -DQUDA_POSIX_THREADS=OFF \
  -DQUDA_QDPJIT=OFF \
  -DQUDA_QIO=OFF \
  -DQUDA_QMP=OFF \
  ${quda_src}

